# Generated by Django 2.2.8 on 2020-06-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('DONOR', 'DONOR'), ('RECIPIENT', 'RECIPIENT')], default='DONOR', max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='listing',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='listing_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
