# Generated by Django 2.2.8 on 2020-06-25 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200123_1023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
