# Generated by Django 2.2.8 on 2020-06-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200623_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='bdsguser',
            name='allowed_blood_groups',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bdsguser',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
