# Generated by Django 2.2.8 on 2020-06-23 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200623_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bdsguser',
            old_name='can_donate_to',
            new_name='can_receive_blood_from',
        ),
    ]
