# Generated by Django 2.2.8 on 2020-06-23 15:08

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200623_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='bdsguser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
