# Generated by Django 2.2.4 on 2020-05-31 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donations', '0003_auto_20200526_0554'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('EXPIRED', 'EXPIRED')], max_length=255)),
                ('blood_group', models.CharField(choices=[('O+', 'O+'), ('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('O-', 'O-'), ('A-', 'A-'), ('B-', 'B-'), ('AB-', 'AB-')], max_length=255)),
                ('donation_type', models.CharField(choices=[('RED_BLOOD_CELLS', 'Red blood cells'), ('PLATELETS', 'Platelets'), ('WHOLE_BLOOD', 'Whole blood'), ('PLASMA', 'Plasma')], max_length=255)),
                ('donated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('donation_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donations.DonationCenter')),
            ],
        ),
        migrations.CreateModel(
            name='DonationRequestAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_status', models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('EXPIRED', 'EXPIRED')], max_length=255)),
                ('appointment_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('donation_request', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='donations.DonationRequest')),
            ],
        ),
        migrations.CreateModel(
            name='UserDonationCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_center', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.PROTECT, to='donations.DonationCenter')),
                ('user', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
