# Generated by Django 2.2.4 on 2020-06-01 07:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_donationrequest_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 7, 11, 44, 526477, tzinfo=utc), max_length=255),
        ),
    ]
