# Generated by Django 2.2.4 on 2020-06-01 07:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_auto_20200601_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 7, 27, 47, 293437, tzinfo=utc), max_length=255),
        ),
    ]
