# Generated by Django 2.2.4 on 2020-06-01 16:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donations', '0007_auto_20200601_0727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationrequest',
            name='donated_by',
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 16, 22, 22, 65889, tzinfo=utc), max_length=255),
        ),
        migrations.AlterField(
            model_name='donationrequestappointment',
            name='appointment_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('EXPIRED', 'EXPIRED')], default='PENDING', max_length=255),
        ),
        migrations.AlterField(
            model_name='donationrequestappointment',
            name='created_by',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
