# Generated by Django 2.2.4 on 2020-06-01 16:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_auto_20200601_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 16, 52, 8, 833040, tzinfo=utc), max_length=255),
        ),
        migrations.AlterField(
            model_name='donationrequestappointment',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
