# Generated by Django 2.2.4 on 2020-06-01 16:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_auto_20200601_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 16, 52, 54, 940208, tzinfo=utc), max_length=255),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('EXPIRED', 'EXPIRED')], default='PENDING', max_length=255),
        ),
    ]
