# Generated by Django 2.2.8 on 2020-06-02 20:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('donations', '0010_auto_20200601_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='donation_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact'),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 2, 20, 56, 55, 732654, tzinfo=utc), max_length=255),
        ),
    ]
