# Generated by Django 2.2.8 on 2020-06-02 21:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0011_auto_20200602_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 2, 21, 7, 52, 812513, tzinfo=utc), max_length=255),
        ),
    ]
