# Generated by Django 2.2.8 on 2020-06-04 19:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0013_auto_20200602_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationcenter',
            name='address',
            field=django_google_maps.fields.AddressField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='donationcenter',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 4, 19, 10, 59, 324717, tzinfo=utc), max_length=255),
        ),
    ]
