# Generated by Django 2.2.8 on 2020-06-06 11:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0014_auto_20200604_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationcenter',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 11, 15, 39, 38298, tzinfo=utc), max_length=255),
        ),
    ]
