# Generated by Django 2.2.8 on 2020-06-21 19:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0016_auto_20200621_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='allowed_blood_groups',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 21, 19, 30, 16, 241260, tzinfo=utc), max_length=255),
        ),
    ]
