# Generated by Django 2.2.8 on 2020-06-21 20:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0017_auto_20200621_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequestappointment',
            name='completed_date',
            field=models.DateTimeField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 21, 20, 36, 53, 624431, tzinfo=utc), max_length=255),
        ),
    ]
