# Generated by Django 2.2.8 on 2020-06-23 05:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0020_auto_20200623_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 23, 5, 31, 43, 734909, tzinfo=utc), max_length=255),
        ),
    ]
