# Generated by Django 2.2.8 on 2020-06-23 15:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0025_auto_20200623_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 23, 15, 8, 54, 780155, tzinfo=utc), max_length=255),
        ),
    ]
