# Generated by Django 2.2.8 on 2020-06-23 16:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0026_auto_20200623_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 23, 16, 2, 14, 793959, tzinfo=utc), max_length=255),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 23, 16, 2, 14, 793934, tzinfo=utc), max_length=255),
        ),
    ]
