# Generated by Django 2.2.8 on 2020-06-23 16:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0027_auto_20200623_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 23, 16, 56, 28, 313771, tzinfo=utc), max_length=255),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='donation_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.BDSGUser'),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 23, 16, 56, 28, 313796, tzinfo=utc), max_length=255),
        ),
    ]
