# Generated by Django 2.2.8 on 2020-06-25 14:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0028_auto_20200623_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 25, 14, 47, 40, 862749, tzinfo=utc), max_length=255),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 25, 14, 47, 40, 862774, tzinfo=utc), max_length=255),
        ),
    ]
