# Generated by Django 2.2.8 on 2020-06-25 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_delete_listing'),
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Realtor',
        ),
    ]
